[Desktop Entry]
Name=MycroftSkillInstaller
Name[ca]=MycroftSkillInstaller
Name[ca@valencia]=MycroftSkillInstaller
Name[cs]=MycroftSkillInstaller
Name[de]=MycroftSkillInstaller
Name[el]=MycroftSkillInstaller
Name[en_GB]=MycroftSkillInstaller
Name[eo]=MycroftSkillInstaller
Name[es]=MycroftSkillInstaller
Name[eu]=MycroftSkillInstaller
Name[fi]=MycroftSkillInstaller
Name[fr]=MycroftSkillInstaller
Name[gl]=MycroftSkillInstaller
Name[hi]=माइक्रॉफ्ट-स्किल-इंस्टॉलर
Name[hu]=MycroftSkillInstaller
Name[is]=MycroftSkillInstaller
Name[it]=MycroftSkillInstaller
Name[ka]=MycroftSkillInstaller
Name[ko]=MycroftSkillInstaller
Name[nl]=MycroftSkillInstaller
Name[nn]=MycroftSkillInstaller
Name[pl]=MycroftSkillInstaller
Name[pt]=MycroftSkillInstaller
Name[pt_BR]=MycroftSkillInstaller
Name[sk]=MycroftSkillInstaller
Name[sl]=MycroftSkillInstaller
Name[sv]=Mycroft Skill installationsverktyg
Name[tr]=MycroftSkillInstaller
Name[uk]=MycroftSkillInstaller
Name[x-test]=xxMycroftSkillInstallerxx
Name[zh_CN]=MycroftSkillInstaller
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=download
Type=Application
NoDisplay=@DesktopNoDisplay@
GenericName=Mycroft Skill Installer
GenericName[ca]=Instal·lador d'habilitats del Mycroft
GenericName[ca@valencia]=Instal·lador d'habilitats de Mycroft
GenericName[cs]=Instalátor dovedností pro Mycroft
GenericName[el]=Εγκατάσταση προγράμματος δεξιοτήτων Mycroft
GenericName[en_GB]=Mycroft Skill Installer
GenericName[eo]=Mycroft Lertec-Instalilo
GenericName[es]=Instalador de habilidades de Mycroft
GenericName[eu]=Mycroft Skill instalatzailea
GenericName[fi]=Mycroftin kykyasentaja
GenericName[fr]=Installateur de compétences Mycroft
GenericName[gl]=Instalador de habilidades de Mycroft
GenericName[hi]=माइक्रॉफ्ट-स्किल-इंस्टॉलर
GenericName[hu]=Mycroft Skill-telepítő
GenericName[is]=Uppsetningarforrit Mycroft Skill
GenericName[it]=Installatore Mycroft Skill
GenericName[ka]=Mycroft Skill-ის დაყენება
GenericName[ko]=Mycroft 스킬 설치기
GenericName[nl]=Installatieprogramma Mycroft Skill
GenericName[nn]=Installering av Mycroft-evner
GenericName[pl]=Wgrywanie umiejętności Mycroft
GenericName[pt]=Instalador de Competências do Mycroft
GenericName[pt_BR]=Instalador de habilidades do Mycroft
GenericName[sk]=Mycroft Skill Installer
GenericName[sl]=Mycroft Skill Installer
GenericName[sv]=Mycroft Skill installationsverktyg
GenericName[tr]=Mycroft Yetenek Kurucu
GenericName[uk]=Засіб встановлення можливостей Mycroft
GenericName[x-test]=xxMycroft Skill Installerxx
GenericName[zh_CN]=Mycroft 功能安装程序
Categories=Qt;KDE;System;Mycroft;Ai;Automation;
Keywords=program;software;mycroft;Ai;skills;automation;
Keywords[ca]=programa;programari;mycroft;Ai;IA;habilitats;automatització;
Keywords[ca@valencia]=programa;programari;mycroft;Ai;IA;habilitats;automatització;
Keywords[cs]=program;software;mycroft;Ai;dovednosti;automatizace;
Keywords[el]=πρόγραμμα;λογισμικό;mycroft;Ai;δεξιότητες;αυτοματισμός;
Keywords[en_GB]=program;software;mycroft;Ai;skills;automation;
Keywords[eo]=programo;programaro;mycroft;Ai;lertecoj;aŭtomatigo;
Keywords[es]=programa;software;mycroft;Ai;Ia;habilidades;automatización;
Keywords[eu]=programa;softwarea;mycroft;Ai;IA;skills;trebetasunak;automatizatzea;
Keywords[fi]=ohjelma;ohjelmisto;mycroft;tekoäly;AI;kyvyt;automaatio;
Keywords[fr]=programme ; logiciel ; mycroft ; AI ; compétences ;automatisation ;
Keywords[gl]=programa;software;mycroft;AI;IA;habilidades;funcionalidades;automatizar;automatización;
Keywords[hi]=अनुप्रयोग;सॉफ्टवेयर;माइक्रॉफ्ट;एआइ;कौशल;स्वचालन;
Keywords[hu]=program;szoftver;mycroft;AI;skillek;automatizálás;
Keywords[is]=forrit;hugbúnaður;mycroft;Ai;skills;sjálfvirkni;
Keywords[it]=programma;software;mycroft;Ai;skill;automazione;
Keywords[ka]=program;software;mycroft;Ai;skills;automation;
Keywords[ko]=program;software;mycroft;Ai;skills;automation;프로그램;소프트웨어;스킬;자동화;
Keywords[nl]=programma;software;mycroft;Ai;vaardigheden;automatisering;
Keywords[nn]=program;programvare;mycroft;Ai;evner;skills;automatisering;
Keywords[pl]=program;oprogramowanie;mycroft;Ai;umiejętności;automatyzacja;
Keywords[pt]=programa;aplicação;mycroft;IA;competências;automação;
Keywords[pt_BR]=programa;software;mycroft;Ai;IA;skills;automação;habilidades;
Keywords[sk]=program;softvér;mycroft;Ai;schopnosti;automatizácia;
Keywords[sl]=program;software;mycroft;umetna inteligenca;veščine;avtomatizacija;
Keywords[sv]=program;programvara;mycroft;AI;färdigheter;automation;
Keywords[tr]=program;yazılım;mycroft;yapay zeka;yetenekler;otomasyon;
Keywords[uk]=program;software;mycroft;Ai;skills;automation;програма;майкрофт;ші;можливості;здібності;навички;
Keywords[x-test]=xxprogramxx;xxsoftwarexx;xxmycroftxx;xxAixx;xxskillsxx;xxautomationxx;
Keywords[zh_CN]=program;software;mycroft;Ai;skills;automation;程序;软件;人工智能;技能;能力;功能;自动化;
