[Desktop Entry]
Name=MycroftSkillInstaller
Name[ca]=MycroftSkillInstaller
Name[ca@valencia]=MycroftSkillInstaller
Name[cs]=MycroftSkillInstaller
Name[de]=MycroftSkillInstaller
Name[en_GB]=MycroftSkillInstaller
Name[es]=MycroftSkillInstaller
Name[eu]=MycroftSkillInstaller
Name[fr]=MycroftSkillInstaller
Name[hi]=माइक्रॉफ्ट-स्किल-इंस्टॉलर
Name[hu]=MycroftSkillInstaller
Name[it]=MycroftSkillInstaller
Name[ko]=MycroftSkillInstaller
Name[nl]=MycroftSkillInstaller
Name[pl]=MycroftSkillInstaller
Name[pt]=MycroftSkillInstaller
Name[sk]=MycroftSkillInstaller
Name[sl]=MycroftSkillInstaller
Name[sv]=Mycroft Skill installationsverktyg
Name[uk]=MycroftSkillInstaller
Name[x-test]=xxMycroftSkillInstallerxx
Name[zh_CN]=MycroftSkillInstaller
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=download
Type=Application
NoDisplay=@DesktopNoDisplay@
GenericName=Mycroft Skill Installer
GenericName[ca]=Instal·lador d'habilitats del Mycroft
GenericName[ca@valencia]=Instal·lador d'habilitats del Mycroft
GenericName[cs]=Instalátor dovedností pro Mycroft
GenericName[en_GB]=Mycroft Skill Installer
GenericName[es]=Instalador de habilidades de Mycroft
GenericName[eu]=Mycroft Skill instalatzailea
GenericName[fr]=Installateur de compétences Mycroft
GenericName[hi]=माइक्रॉफ्ट-स्किल-इंस्टॉलर
GenericName[hu]=Mycroft Skill-telepítő
GenericName[it]=Installatore Mycroft Skill
GenericName[ko]=Mycroft 스킬 설치기
GenericName[nl]=Installatieprogramma Mycroft Skill
GenericName[pl]=Wgrywanie umiejętności Mycroft
GenericName[pt]=Instalador de Competências do Mycroft
GenericName[sk]=Mycroft Skill Installer
GenericName[sl]=Mycroft Skill Installer
GenericName[sv]=Mycroft Skill installationsverktyg
GenericName[uk]=Засіб встановлення можливостей Mycroft
GenericName[x-test]=xxMycroft Skill Installerxx
GenericName[zh_CN]=Mycroft 功能安装程序
Categories=Qt;KDE;System;Mycroft;Ai;Automation;
Keywords=program;software;mycroft;Ai;skills;automation;
Keywords[ca]=programa;programari;mycroft;Ai;IA;habilitats;automatització;
Keywords[ca@valencia]=programa;programari;mycroft;Ai;IA;habilitats;automatització;
Keywords[cs]=program;software;mycroft;Ai;dovednosti;automatizace;
Keywords[en_GB]=program;software;mycroft;Ai;skills;automation;
Keywords[es]=programa;software;mycroft;Ai;Ia;habilidades;automatización;
Keywords[eu]=programa;softwarea;mycroft;Ai;IA;skills;trebetasunak;automatizatzea;
Keywords[fr]=programme ; logiciel ; mycroft ; AI ; compétences ;automatisation ;
Keywords[hi]=अनुप्रयोग;सॉफ्टवेयर;माइक्रॉफ्ट;एआइ;कौशल;स्वचालन;
Keywords[hu]=program;szoftver;mycroft;AI;skillek;automatizálás;
Keywords[it]=programma;software;mycroft;Ai;skill;automazione;
Keywords[ko]=program;software;mycroft;Ai;skills;automation;프로그램;소프트웨어;스킬;자동화;
Keywords[nl]=programma;software;mycroft;Ai;vaardigheden;automatisering;
Keywords[pl]=program;oprogramowanie;mycroft;Ai;umiejętności;automatyzacja;
Keywords[pt]=programa;aplicação;mycroft;IA;competências;automação;
Keywords[sk]=program;softvér;mycroft;Ai;schopnosti;automatizácia;
Keywords[sl]=program;software;mycroft;umetna inteligenca;veščine;avtomatizacija;
Keywords[sv]=program;programvara;mycroft;AI;färdigheter;automation;
Keywords[uk]=program;software;mycroft;Ai;skills;automation;програма;майкрофт;ші;можливості;здібності;навички;
Keywords[x-test]=xxprogramxx;xxsoftwarexx;xxmycroftxx;xxAixx;xxskillsxx;xxautomationxx;
Keywords[zh_CN]=program;software;mycroft;Ai;skills;automation;程序;软件;人工智能;技能;能力;功能;自动化;
